# Generated by Django 4.1.5 on 2023-01-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestudy',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profilestudy',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profilework',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profilework',
            name='start',
            field=models.DateField(),
        ),
    ]
